# Generated by Django 4.2 on 2025-01-09 16:13

import Apps.Catalogos.modalidadesPago.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModalidadPagoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, null=True, unique=True, validators=[Apps.Catalogos.modalidadesPago.models.validar_nombre])),
            ],
            options={
                'verbose_name': 'ModalidadPago',
                'verbose_name_plural': 'ModalidadesPago',
                'db_table': 'TbModalidadPago',
            },
        ),
    ]
