# Generated by Django 4.2 on 2024-12-10 15:50

import Apps.Catalogos.tiposPago.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPagoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True, validators=[Apps.Catalogos.tiposPago.models.validar_nombre])),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'TbTipoPago',
            },
        ),
    ]
