# Generated by Django 4.2 on 2025-01-14 15:40

import Apps.Catalogos.tiposPago.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiposPago', '0002_alter_tipopagomodel_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopagomodel',
            name='nombre',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
