# Generated by Django 4.2 on 2025-01-09 15:34

import Apps.Catalogos.estadosFecha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFechaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'EstadoFecha',
                'verbose_name_plural': 'EstadosFecha',
                'db_table': 'TbEstadoFecha',
            },
        ),
    ]
