# Generated by Django 4.2 on 2025-01-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosFecha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadofechamodel',
            name='nombre',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
