# Generated by Django 4.2 on 2025-01-09 15:21

import Apps.Catalogos.exploraciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExploracionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True, unique=True, validators=[Apps.Catalogos.exploraciones.models.validar_nombre])),
            ],
            options={
                'verbose_name': 'Exploracion',
                'verbose_name_plural': 'Exploraciones',
                'db_table': 'TbExploracion',
            },
        ),
    ]
