# Generated by Django 4.2 on 2025-01-09 15:55

import Apps.Catalogos.estadosPago.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPagoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=12, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'EstadoPago',
                'verbose_name_plural': 'EstadosPago',
                'db_table': 'TbEstadoPago',
            },
        ),
    ]
