# Generated by Django 4.2 on 2025-01-08 20:49

import Apps.Catalogos.frecuencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrecuenciaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Frecuencia',
                'verbose_name_plural': 'Frecuencias',
                'db_table': 'TbFrecuencia',
            },
        ),
    ]
