# Generated by Django 4.2 on 2025-01-16 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generos', '0004_alter_generomodel_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(blank=True, max_length=16, null=True)),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.CharField(max_length=2)),
                ('direccion', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=30)),
                ('antecedentes', models.CharField(max_length=30)),
                ('isdeleted', models.BooleanField(default=False)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generos.generomodel')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'TbPaciente',
            },
        ),
    ]
