# Generated by Django 4.2 on 2025-01-08 21:30

import Apps.Catalogos.periocidades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriocidadModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Periocidad',
                'verbose_name_plural': 'Periocidades',
                'db_table': 'TbPeriocidad',
            },
        ),
    ]
