# Generated by Django 4.2 on 2024-12-02 22:14

import Apps.Catalogos.generos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generomodel',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, validators=[Apps.Catalogos.generos.models.validar_nombre]),
        ),
    ]
