# Generated by Django 4.2 on 2024-12-30 16:50

import Apps.Catalogos.generos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0002_alter_generomodel_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generomodel',
            name='nombre',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
