# Generated by Django 4.2 on 2025-01-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generos', '0003_alter_generomodel_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generomodel',
            name='nombre',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
