# Generated by Django 4.2 on 2025-01-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosCita', '0002_alter_estadocitamodel_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocitamodel',
            name='nombre',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
