# Generated by Django 4.2 on 2025-01-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
                ('encargado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Clinica',
                'verbose_name_plural': 'Clinicas',
                'db_table': 'TbClinica',
            },
        ),
    ]
