# Generated by Django 4.2 on 2025-01-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosCuenta', '0002_alter_estadocuentamodel_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocuentamodel',
            name='nombre',
            field=models.CharField(default=0, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
