# Generated by Django 4.2 on 2025-01-10 15:51

import Apps.Catalogos.montosDescuento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MontoDescuentoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'MontoDescuento',
                'verbose_name_plural': 'MontosDescuento',
                'db_table': 'TbMontoDescuento',
            },
        ),
    ]
