# Generated by Django 4.2 on 2025-01-10 16:41

import Apps.Catalogos.montosDescuento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montosDescuento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montodescuentomodel',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, unique=True),
            preserve_default=False,
        ),
    ]
