# Generated by Django 4.2 on 2025-01-13 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montosDescuento', '0002_alter_montodescuentomodel_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montodescuentomodel',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=5, unique=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
